### ISSUE TITLE
Where to find supported pagers?

### ISSUE THREAD

**Issue by brannondorsey** [unsynchronized/gr-mixalot#10]
Hey there,

Super excited to use `gr-mixalot`. Thanks for doing all of the heavy lifting to get this kind of POCSAG transmission support w/ GRC. In going through your docs it looks like `gr-mixalot` doesn't support FLEX protocols, and most alphanumeric pagers I can't find on the "cheap" online (ebay mostly) are flex only. Do you have a list of known supported devices or a vendor recommendation on where to find a load of POCSAG 512, 1200, and 2400 supported pagers w/ accessible cap codes?

Thanks,
Brannon

**Comment by unsynchronized** [comment]
Hey!  

You're right that gr-mixalot currently only supports POCSAG.  I've got the TX down for GSC (alphanumeric/numeric only), but haven't had the time to rewrite the ECC code (I found some that works, but there's no license) and encode the data streams.  Hope to do some too.  Haven't started on FLEX/ReFLEX yet (but I found the specs).

I've lucked out on finding a bunch of POCSAG pagers on ebay by looking for lots.  I'd suggest searching for specific model names (Motorola Bravo / Advisor are two I've tested with a bit) and more generic terms like "pager lot" or "beeper lot".  In the latter case, there are more results to dig through, but the chances of turning up a $10-15 lot of 10 or so (maybe 3-4 of which will work) is higher.   Doesn't have to be Motorola; I've used a handful of others as well.  The only pager model I've had a warning about issues with are those designed for the Skyper pager network (which is/was operational in Germany).  I haven't tracked one of those down yet.  

Good luck!  If you still can't find one after a while, I can dig through the basement and ship you an old numeric Bravo or something..  Good luck!

**Comment by brannondorsey** [comment]
I found an Advisor II on Ebay that is on its way now :) Bulk is what I am looking for and I've searched around but only found bulk flex or bulk POCSAG numeric. I'll keep looking though. Thanks for the offer to send one though, it is much appreciated :smile:. Maybe in a month or so if I am feeling brave I will look through the FLEX and reFLEX specs and see what I can do.
