### ISSUE TITLE
Weak/irregular broadcast on some machines

### ISSUE THREAD

**Issue by brannondorsey** [unsynchronized/gr-mixalot#14]
Hi there, 

I've been loving gr-mixalot! I have however been experiencing some issues using it on less "beefy" machines like the Raspberry Pi 2 or a dual-core NanoPC. I'm using a hackrf to transmit and an rtl-sdr to monitor that transmission. Everything works fine when I transmit using the hackrf from my Macbook Pro, however both the RPi2 and the NanoPC broadcasts appear "choppy" and irregular and cannot be picked up on the pager that I am broadcasting to. Do you think these machines are just too weak to run the DSP algorithms or do you think there is something else I might be able to do to get gr-mixalot working on them?

Thanks!
Brannon

**Comment by unsynchronized** [comment]
Hmm.. I'm inclined to think that they're just not powerful enough. 

Have you tried reducing the sample rate, by any chance?

**Comment by brannondorsey** [comment]
Oops, forgot to close this. Your guess is indeed correct, the two machines were simply not beefy enough to support the default sampling rate. I was able to lower the rate to a workable speed with the NanoPC, however it seems that the RPi 2 just doesn't have the power to run gr-mixalot reliably. Thanks for the input!
