### ISSUE TITLE
lib/CMakeFiles/gnuradio-mixalot.dir/build.make:62: recipe for target 'lib/CMakeFiles/gnuradio-mixalot.dir/utils.cc.o' failed

### ISSUE THREAD

**Issue by hansnans** [unsynchronized/gr-mixalot#25]
mkdir build
cd build
cmake ../
make

output:
[output.txt](https://github.com/unsynchronized/gr-mixalot/files/1955727/output.txt)

**Comment by hansnans** [comment]
update: checking out commit ad39be84f0282e83ef7e5baf2e938a8f0630c56d make things great again and it works

**Comment by vanhoteen** [comment]
> update: checking out commit [ad39be8](https://github.com/unsynchronized/gr-mixalot/commit/ad39be84f0282e83ef7e5baf2e938a8f0630c56d) make things great again and it works

hello I have reviewed ad39be8 and I have the same, but I have the same error. What is the most concrete solution please?

**Comment by unsynchronized** [comment]
Can you describe the environment on which you're trying to compile it?   It looks like ubuntu - which version?

**Comment by vanhoteen** [comment]
thanks for answering, ubuntu 16.04 Lts
python 2.7.11
GNU Radio 3.7.11

**Comment by unsynchronized** [comment]
I think I fixed it; try commit e7d0f8ec3cd5f10f9f437c31039d7e4c5804503c.

**Comment by vanhoteen** [comment]
Thank you very much, it makes me very excited to try this block.
attached result
