### ISSUE TITLE
pretty please add a license to the repo

### ISSUE THREAD

**Issue by ZeroChaos-** [unsynchronized/gr-mixalot#36]
The repo has been forked to add gnuradio 3.8 support but there is no license on the original repo which makes everything murky.  Even if you don't want to maintain this anymore, please add a permissive license so others can continue your work.

**Comment by ZeroChaos-** [comment]
https://github.com/ckoval7/gr-mixalot.git

**Comment by ZeroChaos-** [comment]
some of the code seems obviously derivative of gnuradio which makes GPL-3 the most appropriate license. to add to the repo.  Other bits of the code are listed as "public-domain".  Unless you have an issue with GPL-3 it would likely be easiest to simply license the whole repo as GPL-3.  I'm not sure if github can officially add a dual license, but you can add a LICENSE file that lists both licenses if you want to keep your code as "public-domain" instead of GPL-3

**Comment by unsynchronized** [comment]
Which parts do you see as obviously derivative of GR?

**Comment by unsynchronized** [comment]
Also, thanks for your work!  I'm happy to merge, and update the `wasp` branch as well (which includes FLEX and remote tuning/paging) if you send a PR.

**Comment by ZeroChaos-** [comment]
I mean a few of the files have an actual gnuradio license on the top....  it's not much detective work
https://github.com/unsynchronized/gr-mixalot/blob/master/lib/qa_mixalot.h
https://github.com/unsynchronized/gr-mixalot/blob/master/lib/qa_mixalot.cc
https://github.com/unsynchronized/gr-mixalot/blob/master/lib/test_mixalot.cc
https://github.com/unsynchronized/gr-mixalot/blob/master/include/mixalot/api.h

other files are additionally listed as licensed under the gpl
https://github.com/unsynchronized/gr-mixalot/blob/master/python/__init__.py

**Comment by ZeroChaos-** [comment]
and yeah, if you want a pr I can compel that PR.  My group has more of a desire to use your work than take over :-)
The PR will look pretty extensive but much of it was just removing unneeded cmake code.

**Comment by unsynchronized** [comment]
Hah, yeah, I just noticed that - I used gr_modtool to create the block initially, which probably generated those

I'm happy to put GPL3 in the license file if that'll make someone happy.

There definitely was a bunch of cmake cruft in there so that it would work on 3.6 and 3.7 at the same time.

**Comment by ZeroChaos-** [comment]
the "correct" way to cmake is to let cmake automatically find the cmake blocks installed by the upstream package rather than replicating them.  this should keep things working properly across both versions as the version you have installed are the cmake files which will be used.  You will see them removed in the PR, and I suspect if you test you will find it works desirably.  Give us a few, @ckoval7 did the majority of the work and will send a PR when he is available.

**Comment by unsynchronized** [comment]
If you're talking about the FindGruel/FindGnuradioCore blocks, those were autogenerated by gr_modtool at the time (2012-2013) and (IIRC) were the best of a bunch of bad options in the 3.6 days (which is why I cloned that approach with IT++).. Definitely not needed by 3.7 though.  

I've added a GPLv3 COPYING file to the main branch and `wasp`.

**Comment by unsynchronized** [comment]
License added - I'm excited for the PR, as I haven't had time to do the cmake changes for 3.8 yet, but I'll happily test and port to the new branch quickly.  Thanks again!
