### ISSUE TITLE
merge gr 3.8 fixes into wasp

### ISSUE THREAD

**Issue by ZeroChaos-** [unsynchronized/gr-mixalot#39]
Thanks for accepting @ckoval7's gr 3.8 PR.  Can you please merge those changes into the wasp branch for testing as well please?  or you are ready to pull wasp into maint-3.8 that's great too.

**Comment by ZeroChaos-** [comment]
Happy New Year :-)

**Comment by unsynchronized** [comment]
Hey: Pong.  Finally getting to this, and bringing in GSC as well.

**Comment by ZeroChaos-** [comment]
Heh, cool.  I'm getting ready to test GR 3.9 :-D

**Comment by unsynchronized** [comment]
Yeah, totally; I'll do that after everything is working on 3.8.

At the moment I'm working on the wasp-3.8 branch -- currently bringing in an old GSC implementation I did.

**Comment by ZeroChaos-** [comment]
awesome, I'd love to see the work merged so we can enjoy all the features at once :-)  thanks!

**Comment by unsynchronized** [comment]
OK, this is done.  Give it a shot and let me know if you have any issues.

The main branch is now called 'main', and this currently has the same stuff as maint-3.8.
There is now a new maint-3.7 branch (and a v3.7 tag) for pre-3.8 code.

I've updated the README to add some usage info for the PDU server.  This doesn't support GSC yet, but the GSC single-shot transmitter block works.
