### ISSUE TITLE
osmo-fl2k?

### ISSUE THREAD

**Issue by RandomPSPguy** [unsynchronized/gr-mixalot#47]
Am I able to use the osmo-fl2k with this software? If so how would I set that up?

**Comment by unsynchronized** [comment]
Sorry, just saw this.

The osmo-fl2k looks like a super neat discovery + hack.  If it's available in the osmocom GR sink, I don't see why it wouldn't work!

Were you able to have any success?  I might still be able to help if so.

**Comment by RandomPSPguy** [comment]
Sorry I am new to SDR so I didn't exactly know what is needed for all of this yet. I closed this because while the osmo is interesting, I found it would be too much of a headache to setup and it has it's own issues so I decided to not purchase it.

I was looking for the lowest barrier to entry to set this up. I found raspberry pi [rpitx with gnu radio support ](https://github.com/jmfriedt/gr-rpitx) and plan on using that now, it is by far the cheapest option for a transmitter and as I understand should work fine with this awesome software. All one would need is a pi zero with a wire and good filters. 

Thanks for this software btw, I haven't used it yet but it has exactly everything I wanted included.

Btw, I've read in the issue pages that a while back you said you had the specs for Re-Flex and planned on implementing them. Do you still have plans to do that? No rush of course, I'm just fascinated by those pagewriters and would love to try one out someday.

Finally, just a suggestion, maybe add support for older protocols like whatever the pageboy and motorola sensar used?
