### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Manawyrm** [unsynchronized/gr-mixalot#5]
.

**Comment by unsynchronized** [comment]
Hi!  Sorry for the delay in getting back to you; I'm currently traveling.  

Unfortunately I haven't worked with that vendor+device combo before, so I'm not sure exactly where the capcode might be.  One thing I'd try first, if you happen to live near the area where it was active, is monitoring that channel + others nearby to see if you can decode any transmissions.  That may give some clue.

There also may be a test mode on the device that could use to dump the code.  I found some old docs on these while googling.. may be of use: http://urgentcomm.com/mag/servicing-tips-bravo-family-pagers-identification-frequency-changes-logic-board-modifications-an

Have you tried 2400 baud?

Also, have you tried capcode 337586?

Good luck,
--cstone
